name: Daily MongoDB Live Simulations

on:
  schedule:
    - cron: '14 14 * * *'  # CHANGE this to your UTC+1 time now for testing
  workflow_dispatch:       # manual trigger option

jobs:
  run-live-simulations:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scripts

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Simulation Live Data Script
        run: python simulation_data_live.py

      - name: Run Simulation Prediction Live Script
        run: python simulation_prediction_live.py
